config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'corporates#index'
  resources :corporates, only: [:index, :new, :create, :show, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/corporate.rb
class Corporate < ApplicationRecord
  validates :name, presence: true
  validates :industry, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end
end

app/controllers/corporates_controller.rb
class CorporatesController < ApplicationController
  protect_from_forgery except: :update
  def index
    @corporates = Corporate.all
  end

  def new
    @corporate = Corporate.new
  end

  def create
    @corporate = Corporate.create(corporate_params)
    if @corporate.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @corporate = Corporate.find(params[:id])
  end

  def update
    @corporate = Corporate.find(params[:id])
    redirect_to corporate_path(@corporate.id) if @corporate.update(corporate_params)
  end

  def destroy
    @corporate = Corporate.find(params[:id])
    @corporate.destroy
    redirect_to root_path
  end

  private

  def corporate_params
    params.require(:corporate).permit(:name, :industry, :capital, :earnings, :employee, :place, :average_income, :average_age,
                                      :business_content, :human_resource, :strength, :weakness, :selection_method, :others)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/corporates_helper.rb
module CorporatesHelper
end

app/views/corporates/index.html.erb
<header class='header'>
  <%= link_to image_tag(asset_path("recruitment_logo_color"), class:"header-logo"), "/"  %>
</header>

<div class='main'>
  <div class='corporate-display'>
    <ul class='corporate-list'>
      <% if Corporate.exists? %>
        <% @corporates.each do |corporate| %>
          <li class='list'>
            <%= link_to corporate_path(corporate.id), class:'corporate-link' do %>
              <h2 class='list-title'>
                <%= corporate.name %>
              </h2>
              <div class='corporate-info'>
                <p class='corporate-data'>
                  <%= corporate.industry %>
                </p>
                <p class='corporate-data'>
                  <%= corporate.capital %>
                </p>
                <p class='corporate-data'>
                  <%= corporate.earnings %>
                </p>
                <p class='corporate-data'>
                  <%= corporate.employee %>
                </p>
                <p class='corporate-data'>
                  <%= corporate.place %>
                </p>
                <p class='corporate-data'>
                  <%= corporate.average_income %>
                </p>
                <p class='corporate-data'>
                  <%= corporate.average_age %>
                </p>
                <p class='corporate-data'>
                  <%= corporate.business_content %>
                </p>
                <p class='corporate-data'>
                  <%= corporate.human_resource %>
                </p>
                <p class='corporate-data'>
                  <%= corporate.strength %>
                </p>
                <p class='corporate-data'>
                  <%= corporate.weakness %>
                </p>
                <p class='corporate-data'>
                  <%= corporate.selection_method %>
                </p>
                <p class='corporate-data'>
                  <%= corporate.others %>
                </p>
              </div>
            <% end %>
          </li>
        <% end %>
      <% else %>
        <p class='top-message'>気になる業界・業種の企業を調査して情報をまとめよう！</p>
      <% end %>
    </ul>
    <%= link_to image_tag(asset_path("form_btn"), class:"form-btn-icon"), new_corporate_path %>
  </div>
</div>

<footer class='footer'>
  <%= link_to image_tag(asset_path("recruitment_logo_white"), class:"footer-logo"), "/"  %>
  <p>©️ 2022 tamagokakepiza</p>
</footer>

app/views/corporates/new.html.erb
<header class='header'>
  <%= link_to image_tag(asset_path("recruitment_logo_color"), class:"header-logo"), "/"  %>
</header>

<div class='main'>
  
  <div class='form-box'>
    <h2 class='new-page-title'>調査した企業情報を入力しよう！</h2>
    <%= form_with model: @corporate, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <div class='corporate-box'>
      <div class='corporate-name'>
        <span class='form-text'>企業名</span>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :name, class:'corporate-text', id:'corporate_name', placeholder:'企業の正式名称を入力しよう(必須)', maxlength:'150' %>
    </div>
    <div class='corporate-box'>
      <div class='corporate-industry'>
        <span class='form-text'>業界・業種</span>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :industry, class:'corporate-text', id:'corporate_industry', placeholder:'企業の業界・業種を入力しよう(必須)', maxlength:'50' %>
    </div>
    <div class='corporate-box'>
      <div class='corporate-capital'>
        <span class='form-text'>資本金</span>
        <span class="arbitrary">任意</span>
      </div>
      <%= f.text_field :capital, class:'corporate-text', id:'corporate_capital', placeholder:'企業の資本金を調査しよう(任意)', maxlength:'50' %>
    </div>
    <div class='corporate-box'>
      <div class='corporate-earnings'>
        <span class='form-text'>売上高</span>
        <span class="arbitrary">任意</span>
      </div>
      <%= f.text_field :earnings, class:'corporate-text', id:'corporate_earnings', placeholder:'企業の売上高を調査しよう(任意)', maxlength:'50' %>
    </div>
    <div class='corporate-box'>
      <div class='corporate-employee'>
        <span class='form-text'>社員数</span>
        <span class="arbitrary">任意</span>
      </div>
      <%= f.text_field :employee, class:'corporate-text', id:'corporate_employee', placeholder:'企業の社員数を調査しよう(任意)', maxlength:'50' %>
    </div>
    <div class='corporate-box'>
      <div class='corporate-place'>
        <span class='form-text'>本社の場所</span>
        <span class="arbitrary">任意</span>
      </div>
      <%= f.text_field :place, class:'corporate-text', id:'corporate_place', placeholder:'本社の場所を調査しよう(任意)', maxlength:'50' %>
    </div>
    <div class='corporate-box'>
      <div class='corporate-average-income'>
        <span class='form-text'>平均収入</span>
        <span class="arbitrary">任意</span>
      </div>
      <%= f.text_field :average_income, class:'corporate-text', id:'corporate_average_income', placeholder:'企業の平均収入を調査しよう(任意)', maxlength:'50' %>
    </div>
    <div class='corporate-box'>
      <div class='corporate-average-age'>
        <span class='form-text'>平均年齢</span>
        <span class="arbitrary">任意</span>
      </div>
      <%= f.text_field :average_age, class:'corporate-text', id:'corporate_average_age', placeholder:'企業の平均年齢を調査しよう(任意)', maxlength:'50' %>
    </div>
    <div class='corporate-box'>
      <div class='corporate-business_content'>
        <span class='form-text'>事業内容</span>
        <span class="arbitrary">任意</span>
      </div>
      <%= f.text_area :business_content, class:'corporate-text', id:'corporate_business_content', placeholder:'企業の事業内容を調査しよう(任意)', maxlength:'1000' %>
    </div>
    <div class='corporate-box'>
      <div class='corporate-human_resource'>
        <span class='form-text'>求める人材</span>
        <span class="arbitrary">任意</span>
      </div>
      <%= f.text_area :human_resource, class:'corporate-text', id:'corporate_human_resource', placeholder:'企業が求めている人材を調査しよう(任意)', maxlength:'1000' %>
    </div>
    <div class='corporate-box'>
      <div class='corporate-strength'>
        <span class='form-text'>企業の強み</span>
        <span class="arbitrary">任意</span>
      </div>
      <%= f.text_area :strength, class:'corporate-text', id:'corporate_strength', placeholder:'企業の強みを調査しよう(任意)', maxlength:'1000' %>
    </div>
    <div class='corporate-box'>
      <div class='corporate-weakness'>
        <span class='form-text'>企業の弱み</span>
        <span class="arbitrary">任意</span>
      </div>
      <%= f.text_area :weakness, class:'corporate-text', id:'corporate_weakness', placeholder:'企業の弱みを調査しよう(任意)', maxlength:'1000' %>
    </div>
    <div class='corporate-box'>
      <div class='corporate-selection-method'>
        <span class='form-text'>選考方法</span>
        <span class="arbitrary">任意</span>
      </div>
      <%= f.text_area :selection_method, class:'corporate-text', id:'corporate_selection_method', placeholder:'企業の選考方法を調査しよう(任意)', maxlength:'1000' %>
    </div>
    <div class='corporate-box'>
      <div class='corporate-others'>
        <span class='form-text'>その他</span>
        <span class="arbitrary">任意</span>
      </div>
      <%= f.text_area :others, class:'corporate-text', id:'corporate_others', placeholder:'その他にまとめておきたい内容を入力しよう(任意)', maxlength:'2000' %>
    </div>
    <div class='form-btn-box'>
      <%= f.submit '保存', class:'form-btn' %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <% end %>
  </div>
</div>

<footer class='footer'>
  <%= link_to image_tag(asset_path("recruitment_logo_white"), class:"footer-logo"), "/"  %>
  <p>©️ 2022 tamagokakepiza</p>
</footer>

app/views/corporates/show.html.erb
<header class='header'>
  <%= link_to image_tag(asset_path("recruitment_logo_color"), class:"header-logo"), "/"  %>
</header>

<input style="display: none;" id="js-corporate-id" value=<%= @corporate.id %>>
<div class='main'>
  <div class='corporate-show'>
    <%= form_with model: @corporate, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object, id:'error' %>
    <div class='list-title-show'>
      <h2 class='corporate-data'>
        <%= @corporate.name %>
      </h2>
      <div id="js-textarea-corporate" class="list-title-edit">
        <%= f.text_field :name, style:"display: none;", value:@corporate.name, class:'corporate-text', id:'corporate_name', placeholder:'企業の正式名称を入力しよう(必須)', maxlength:'150' %>
      </div>
    </div>
    <div class='corporate-info'>
      <p class='corporate-data'>
        <%= @corporate.industry %>
      </p>
      <%= f.text_field :industry, style:"display: none;", value:@corporate.industry, class:'corporate-text', id:'corporate_industry', placeholder:'企業の業界・業種を入力しよう(必須)', maxlength:'50' %>
      <p class='corporate-data'>
        <%= @corporate.capital %>
      </p>
      <%= f.text_field :capital, style:"display: none;", value:@corporate.capital, class:'corporate-text', id:'corporate_capital', placeholder:'企業の資本金を調査しよう(任意)', maxlength:'50' %>
      <p class='corporate-data'>
        <%= @corporate.earnings %>
      </p>
      <%= f.text_field :earnings, style:"display: none;", value:@corporate.earnings, class:'corporate-text', id:'corporate_earnings', placeholder:'企業の売上高を調査しよう(任意)', maxlength:'50' %>
      <p class='corporate-data'>
        <%= @corporate.employee %>
      </p>
      <%= f.text_field :employee, style:"display: none;", value:@corporate.employee, class:'corporate-text', id:'corporate_employee', placeholder:'企業の社員数を調査しよう(任意)', maxlength:'50' %>
      <p class='corporate-data'>
        <%= @corporate.place %>
      </p>
      <%= f.text_field :place, style:"display: none;", value:@corporate.place, class:'corporate-text', id:'corporate_place', placeholder:'本社の場所を調査しよう(任意)', maxlength:'50' %>
      <p class='corporate-data'>
        <%= @corporate.average_income %>
      </p>
      <%= f.text_field :average_income, style:"display: none;", value:@corporate.average_income, class:'corporate-text', id:'corporate_average_income', placeholder:'企業の平均収入を調査しよう(任意)', maxlength:'50' %>
      <p class='corporate-data'>
        <%= @corporate.average_age %>
      </p>
      <%= f.text_field :average_age, style:"display: none;", value:@corporate.average_age, class:'corporate-text', id:'corporate_average_age', placeholder:'企業の平均年齢を調査しよう(任意)', maxlength:'50' %>
      <p class='corporate-data'>
        <%= @corporate.business_content %>
      </p>
      <%= f.text_area :business_content, style:"display: none;", value:@corporate.business_content, class:'corporate-text', id:'corporate_business_content', placeholder:'企業の事業内容を調査しよう(任意)', maxlength:'1000' %>
      <p class='corporate-data'>
        <%= @corporate.human_resource %>
      </p>
      <%= f.text_area :human_resource, style:"display: none;", value:@corporate.human_resource, class:'corporate-text', id:'corporate_human_resource', placeholder:'企業が求めている人材を調査しよう(任意)', maxlength:'1000' %>
      <p class='corporate-data'>
        <%= @corporate.strength %>
      </p>
      <%= f.text_area :strength, style:"display: none;", value:@corporate.strength, class:'corporate-text', id:'corporate_strength', placeholder:'企業の強みを調査しよう(任意)', maxlength:'1000' %>
      <p class='corporate-data'>
        <%= @corporate.weakness %>
      </p>
      <%= f.text_area :weakness, style:"display: none;", value:@corporate.weakness, class:'corporate-text', id:'corporate_weakness', placeholder:'企業の弱みを調査しよう(任意)', maxlength:'1000' %>
      <p class='corporate-data'>
        <%= @corporate.selection_method %>
      </p>
      <%= f.text_area :selection_method, style:"display: none;", value:@corporate.selection_method, class:'corporate-text', id:'corporate_selection_method', placeholder:'企業の選考方法を調査しよう(任意)', maxlength:'1000' %>
      <p class='corporate-data'>
        <%= @corporate.others %>
      </p>
      <%= f.text_area :others, style:"display: none;", value:@corporate.others, class:'corporate-text', id:'corporate_others', placeholder:'その他にまとめておきたい内容を入力しよう(任意)', maxlength:'2000' %>
    <li class='error-message' style="display: none;" id="name-error-message">Name can't be blank</li>
    <li class='error-message' style="display: none;" id="industry-error-message">Industry can't be blank</li>
      <div id="button-box">
        <div class='form-btn-box'>
          <span class="form-btn", id="js-edit-corporate-btn">編集</span>
          <%=link_to 'もどる', root_path, class:"back-btn" %>
          <%=link_to '削除', "#", method: :delete, class:"delete-btn" %>
        </div>
      </div>
      <div class='form-btn-box' id="js-corporate-button" style="display: none;">
        <button data-update type="submit" id = "save-id" class="form-btn">変更</button>
        <button data-cancel type="button" id = "cancel-id" class="edit-back-btn">キャンセル</button>
      </div>
    </div>
    <% end %>
  </div>
</div>

<footer class='footer'>
  <%= link_to image_tag(asset_path("recruitment_logo_white"), class:"footer-logo"), "/"  %>
  <p>©️ 2022 tamagokakepiza</p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecruitmentApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>